language: php

branches:
  only:
    - master
    - 5.x

php:
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer --version
  - composer install --no-interaction

script:
  - mkdir build
  - mkdir test/attachments/dir/dirdept
  - ./vendor/bin/phpunit -c test/phpunit.xml --coverage-clover build/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/ ./config

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
